#!/usr/bin/env bash

bench() {
  wrk -t4 -c30 -r50000 http://127.0.0.1:8000$1 \
    | grep "Requests/sec" \
    | cut -d ':' -f 2 \
    | xargs echo "$2:"
}

pure_node() {
  bench / "Node.js"
}

express() {
  bench / "Express"
}

pure_http() {
  bench / "pure http"
}

easy_web() {
  bench / "EasyWeb"
  bench /subapp/hello "Subapp"
}

with() {
  node ./bench/$1 &
  local pid=$!
  sleep .5
  $2
  kill $pid
  sleep .5
}

with node.js pure_node
with pure-http.js pure_http
with express.js express
with easy-web.js easy_web
