#!/bin/bash

bench() {
    wrk -t4 -c20 -d5s http://127.0.0.1:8000$1 \
        | grep "Requests/sec" \
        | cut -d ':' -f 2 \
        | xargs echo
}


with() {
    node ./bench/$1 > /dev/null 2>&1 &
    local pid=$!
    sleep .5
    if ! kill -s 0 $pid > /dev/null 2>&1; then
        echo "$2" ":" "Not available"
    else
        local name=$2
        shift; shift
        echo "$name" ":" $($@)
        kill $pid
        wait $pid 2>/dev/null
    fi
}


echo
echo Hello world servers
echo

with hello/easy-web.js "EasyWeb" bench /
with hello/node.js     "Node   " bench /
with hello/koa.js      "Koa    " bench /
with hello/express.js  "Express" bench /

echo
